// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 同步玩家ID
type SyncPlayerID struct {
	PlayerID             int32    `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncPlayerID) Reset()         { *m = SyncPlayerID{} }
func (m *SyncPlayerID) String() string { return proto.CompactTextString(m) }
func (*SyncPlayerID) ProtoMessage()    {}
func (*SyncPlayerID) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *SyncPlayerID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncPlayerID.Unmarshal(m, b)
}
func (m *SyncPlayerID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncPlayerID.Marshal(b, m, deterministic)
}
func (m *SyncPlayerID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncPlayerID.Merge(m, src)
}
func (m *SyncPlayerID) XXX_Size() int {
	return xxx_messageInfo_SyncPlayerID.Size(m)
}
func (m *SyncPlayerID) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncPlayerID.DiscardUnknown(m)
}

var xxx_messageInfo_SyncPlayerID proto.InternalMessageInfo

func (m *SyncPlayerID) GetPlayerID() int32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

// 位置信息
type Position struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	V                    float32  `protobuf:"fixed32,4,opt,name=v,proto3" json:"v,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Position) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Position) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *Position) GetV() float32 {
	if m != nil {
		return m.V
	}
	return 0
}

// 广播消息
type BroadCast struct {
	PlayerID    int32 `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	MessageType int32 `protobuf:"varint,2,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*BroadCast_Content
	//	*BroadCast_Pos
	//	*BroadCast_ActionData
	Data                 isBroadCast_Data `protobuf_oneof:"Data"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BroadCast) Reset()         { *m = BroadCast{} }
func (m *BroadCast) String() string { return proto.CompactTextString(m) }
func (*BroadCast) ProtoMessage()    {}
func (*BroadCast) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *BroadCast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadCast.Unmarshal(m, b)
}
func (m *BroadCast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadCast.Marshal(b, m, deterministic)
}
func (m *BroadCast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadCast.Merge(m, src)
}
func (m *BroadCast) XXX_Size() int {
	return xxx_messageInfo_BroadCast.Size(m)
}
func (m *BroadCast) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadCast.DiscardUnknown(m)
}

var xxx_messageInfo_BroadCast proto.InternalMessageInfo

func (m *BroadCast) GetPlayerID() int32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *BroadCast) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

type isBroadCast_Data interface {
	isBroadCast_Data()
}

type BroadCast_Content struct {
	Content string `protobuf:"bytes,3,opt,name=Content,proto3,oneof"`
}

type BroadCast_Pos struct {
	Pos *Position `protobuf:"bytes,4,opt,name=Pos,proto3,oneof"`
}

type BroadCast_ActionData struct {
	ActionData int32 `protobuf:"varint,5,opt,name=ActionData,proto3,oneof"`
}

func (*BroadCast_Content) isBroadCast_Data() {}

func (*BroadCast_Pos) isBroadCast_Data() {}

func (*BroadCast_ActionData) isBroadCast_Data() {}

func (m *BroadCast) GetData() isBroadCast_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BroadCast) GetContent() string {
	if x, ok := m.GetData().(*BroadCast_Content); ok {
		return x.Content
	}
	return ""
}

func (m *BroadCast) GetPos() *Position {
	if x, ok := m.GetData().(*BroadCast_Pos); ok {
		return x.Pos
	}
	return nil
}

func (m *BroadCast) GetActionData() int32 {
	if x, ok := m.GetData().(*BroadCast_ActionData); ok {
		return x.ActionData
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BroadCast) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BroadCast_Content)(nil),
		(*BroadCast_Pos)(nil),
		(*BroadCast_ActionData)(nil),
	}
}

// 世界聊天
type Talk struct {
	Content              string   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Talk) Reset()         { *m = Talk{} }
func (m *Talk) String() string { return proto.CompactTextString(m) }
func (*Talk) ProtoMessage()    {}
func (*Talk) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *Talk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Talk.Unmarshal(m, b)
}
func (m *Talk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Talk.Marshal(b, m, deterministic)
}
func (m *Talk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Talk.Merge(m, src)
}
func (m *Talk) XXX_Size() int {
	return xxx_messageInfo_Talk.Size(m)
}
func (m *Talk) XXX_DiscardUnknown() {
	xxx_messageInfo_Talk.DiscardUnknown(m)
}

var xxx_messageInfo_Talk proto.InternalMessageInfo

func (m *Talk) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*SyncPlayerID)(nil), "pb.SyncPlayerID")
	proto.RegisterType((*Position)(nil), "pb.Position")
	proto.RegisterType((*BroadCast)(nil), "pb.BroadCast")
	proto.RegisterType((*Talk)(nil), "pb.Talk")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0x63, 0x37, 0x29, 0xcd, 0x6b, 0x58, 0x3c, 0x59, 0x9d, 0xac, 0x4c, 0x88, 0x21, 0x03,
	0x9c, 0x80, 0xb4, 0x43, 0x18, 0x90, 0x22, 0xd3, 0x0b, 0x38, 0xc5, 0x42, 0x15, 0x25, 0xb6, 0x62,
	0xab, 0xaa, 0x7b, 0x24, 0x36, 0x6e, 0x88, 0x9e, 0x43, 0x4b, 0x26, 0x26, 0xfb, 0xfb, 0x6d, 0xbd,
	0xef, 0xd7, 0x83, 0xdb, 0x4f, 0xed, 0x9c, 0x7a, 0xd7, 0x95, 0x1d, 0x8c, 0x37, 0x8c, 0xda, 0xae,
	0xbc, 0x87, 0xe2, 0x35, 0xf4, 0xbb, 0xf6, 0xa0, 0x82, 0x1e, 0x9e, 0x37, 0x6c, 0x05, 0x0b, 0xfb,
	0x7b, 0xe7, 0x44, 0x90, 0xbb, 0x4c, 0x5e, 0xb9, 0xac, 0x61, 0xd1, 0x1a, 0xb7, 0xf7, 0x7b, 0xd3,
	0xb3, 0x02, 0xc8, 0x29, 0x7e, 0xa0, 0x92, 0x9c, 0x90, 0x02, 0xa7, 0x23, 0x05, 0xa4, 0x33, 0x9f,
	0x8d, 0x74, 0x46, 0x3a, 0xf2, 0x74, 0xa4, 0x63, 0xf9, 0x4d, 0x20, 0xaf, 0x07, 0xa3, 0xde, 0xd6,
	0xca, 0xf9, 0xff, 0x6c, 0x4c, 0xc0, 0xf2, 0x65, 0xac, 0xbb, 0x0d, 0x56, 0xc7, 0xe9, 0x99, 0x9c,
	0x46, 0x6c, 0x05, 0x37, 0x6b, 0xd3, 0x7b, 0xdd, 0xfb, 0x68, 0xcb, 0x9b, 0x44, 0x5e, 0x02, 0x26,
	0x60, 0xd6, 0x1a, 0x17, 0xbd, 0xcb, 0x87, 0xa2, 0xb2, 0x5d, 0x75, 0xa9, 0xde, 0x24, 0x12, 0x9f,
	0x98, 0x00, 0x78, 0xda, 0x61, 0xb0, 0x51, 0x5e, 0xf1, 0x0c, 0xc7, 0x37, 0x89, 0x9c, 0x64, 0xf5,
	0x1c, 0x52, 0x3c, 0x4b, 0x01, 0xe9, 0x56, 0x1d, 0x3e, 0x18, 0xff, 0xf3, 0x61, 0xd9, 0xfc, 0x6a,
	0xab, 0xb3, 0x2f, 0x4a, 0xdb, 0xae, 0x9b, 0xc7, 0xbd, 0x3e, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x63, 0xd3, 0x0d, 0x13, 0x68, 0x01, 0x00, 0x00,
}
